- hosts: k3s-nodes-rk
  become: true
  tasks:
    - name: Install the package "armbian-config"
      apt:
        name: armbian-config
        update_cache: yes
        force_apt_get: yes
        force: yes
