- hosts: k3s-agents
  become: true
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: resources/agent.ksh
        dest: /tmp
        owner: root
        group: root
        mode: '0777'
    - name: Install K3s Agent and setup
      ansible.builtin.command: /tmp/agent.ksh