- hosts: k3s-agents
  become: true
  tasks:
    - name: Install K3s Agent and setup
      ansible.builtin.command: curl -sfL https://get.k3s.io | K3S_URL=https://myserver:6443 K3S_TOKEN=K109e863db17c69de0805fd94bb4f857b01fc18aed21a46cd032d11bbbd6e2636d6::server:e10465ea7f2cf629f8d5ffd0c0ebb729 sh -
