- hosts: all-linux-servers
  become: true
  tasks:
    - name: Install the package "mosquitto-clients"
      apt:
        name: mosquitto-clients
        update_cache: yes
        force_apt_get: yes
        state: present
        force: yes
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: resources/process-info-mqtt-pub.sh
        dest: /etc/semaphore/
        owner: semaphore
        group: semaphore
        mode: '0777'
    - name: Ensure a data is published every minute"
      ansible.builtin.cron:
        name: "Send monitoring data"
        job: "/etc/semaphore/process-info-mqtt-pub.sh > /dev/null"
