- hosts: k3s-all-nodes
  become: true
  tasks:
    - name: Update all packages
      apt:
        update_cache: yes
        upgrade: yes
    - name: Reboot machine and send a message
      ansible.builtin.reboot:
        msg: "Rebooting machine in 5 seconds"
